language: cpp

sudo: false

compiler:
    - gcc
    - clang

addons:
  apt:
      packages:
            - libboost-all-dev

script: 
    - mkdir -p release
    - pushd release
    - cmake --version
    - cmake ..
    - make
    - popd

before_install:
    - apt-cache search cmake 
    - apt-cache search boost
    - apt-get install -y libboost-all-dev cmake doxygen g++
    - git submodule update --init src/lib/cli_cpp/thirdparty/pugixml

