language: cpp

compiler:
    - gcc
    - clang

script: 
    - mkdir -p release
    - pushd release
    - cmake ..
    - make
    - popd

before_install:
    - sudo apt-add-repository ppa:boost-latest/ppa -y
    - sudo apt-add-repository ppa:afrank/boost -y
    - sudo apt-add-repository ppa:george-edison55/cmake-3.x -y
    - sudo apt-get update -qq
    - sudo apt-get install -y libboost1.57-all-dev cmake doxygen g++
    - git submodule update --init src/lib/cli_cpp/thirdparty/pugixml

