language: cpp

sudo: required
dist: trusty

compiler:
    - gcc
    - clang

addons:
  apt:
      packages:
            - libboost-all-dev
            - cmake
            - doxygen

script: 
    - mkdir -p release
    - pushd release
    - cmake ..
    - make
    - ./bin/cli_cpp_unit_tests
    - popd

before_install:
    - git submodule update --init src/lib/cli_cpp/thirdparty/pugixml

