language: cpp

compiler:
    - gcc
    - clang

script: 
    - mkdir -p release
    - pushd release
    - cmake ..
    - make
    - popd

before_install:
    - sudo apt-add-repository ppa:boost-latest/ppa -y
    - sudo apt-get update -qq
    - sudo apt-get install -y libboost-all-dev cmake doxygen 


