language: cpp

sudo: false

compiler:
    - gcc
    - clang

script: 
    - mkdir -p release
    - pushd release
    - cmake --version
    - cmake ..
    - make
    - popd

before_install:
    - sudo apt-cache search cmake 
    - sudo apt-get install -y libboost-all-dev cmake doxygen g++
    - git submodule update --init src/lib/cli_cpp/thirdparty/pugixml

