language: cpp

sudo: required
dist: trusty

compiler:
    - gcc
    - clang

addons:
  apt:
      packages:
            - libboost-all-dev
            - cmake
            - doxygen

script: 
    - mkdir -p release
    - pushd release
    - cmake --version
    - cmake ..
    - make
    - popd

before_install:
    - uname -a
    - lsb_release -a
    - apt-cache search cmake 
    - apt-cache search boost
    - git submodule update --init src/lib/cli_cpp/thirdparty/pugixml

